apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: Test-akssecret
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: azureClientID
          objectType: secret
        - |
          objectName: azureClientSecret
          objectType: secret
    tenantId: xxxxxxxxxxx
  secretObjects:
    - secretName: azure-credentials
      type: Opaque
      data:
        - objectName: azureClientID
          key: clientID
        - objectName: azureClientSecret
          key: clientSecret
